version: '3.7'
services:
    mongo:
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            # - /usr/local/mongodb:/data/db
            - './.volumes/mongo:/data/db'
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - '8081:8081'
        environment:
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        depends_on:
            - mongo
    micro-rest-api:
        build:
            context: ./packages/micro-rest-api/
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - mongo
        working_dir: /app
        environment:
            CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            CONFIG_MONGO_DB_NAME: scrappingQueries
            CONFIG_MONGO_DB_TABLE: queries
            CONFIG_MICRO_SERVICE_PORT: 5000
        volumes:
            - ./packages/micro-rest-api:/app
        command: sh -c "npm run dev"
        ports:
            - '5000:5000'
    micro-scraper:
        build:
            context: ./packages/micro-scraper/
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - micro-rest-api
        working_dir: /app
        environment:
            CONFIG_MICRO_SERVICE_PORT: 5001
        volumes:
            - ./packages/micro-scraper:/app
        command: sh -c "npm run dev"
        ports:
            - '5001:5001'
            - '9222:9222'
            - '9229:9229'
    frontend-admin:
        build:
            context: ./packages/frontend-admin/
            dockerfile: Dockerfile
        restart: always
        working_dir: /app
        ports:
            - '3000:3000'
        volumes:
            - ./packages/frontend-admin:/app
        command: sh -c "npm start"
