version: '3.7'
services:
    micro-rest-api:
        image: ghcr.io/kubek93/www-scrapper-micro-rest-api:latest
        restart: always
        environment:
            API_SCRAPER: http://micro-scraper:5001
            CONFIG_MONGODB_URL: mongodb+srv://home_projects_user:SU4U0q3SvZnJaL9M@node-applications.jgoct.mongodb.net/
            CONFIG_MONGO_DB_NAME: micro-scrapper
            CONFIG_MONGO_DB_TABLE: queries
            CONFIG_MICRO_SERVICE_PORT: 5000
        ports:
            - '5000:5000'
    micro-scraper:
        image: ghcr.io/kubek93/www-scrapper-micro-scraper:latest
        restart: always
        depends_on:
            - micro-rest-api
        environment:
            CONFIG_MICRO_SERVICE_PORT: 5001
        expose:
            - '5001'
    frontend-admin:
        image: ghcr.io/kubek93/www-scrapper-frontend-admin:latest
        restart: always
        depends_on:
            - micro-rest-api
        environment:
            REACT_APP_API_URL: http://localhost:5000
        ports:
            - '3000:3000'
