name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '12'
      - name: Check repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install deps and run
        run: |
          cd ./place/to/clone/repo/into
          npm install
          npm start
