name: remote ssh command
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_PROD_HOST }}
        username: ${{ secrets.SERVER_PROD_USERNAME }}
        password: ${{ secrets.SERVER_PROD_PASSWORD }}
        port: ${{ secrets.SERVER_PROD_PORT }}
        script: cd /root && docker-compose down && docker-compose pull && docker-compose up -d --force-recreate
